name: Webapp Testing for Writtenss

on:
  pull_request:
    branches:
      - main  

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Shutdown Default MySQL
      run: sudo service mysql stop

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql-version: '5.7' # Specify the MySQL version you want
        mysql-root-password: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Set your root password in secrets
        mysql-database: ${{ secrets.DATAB_NAME }} # Your database name
        mysql-user: ${{ secrets.DATAB_USER }} # Your database user
        mysql-password: ${{ secrets.DATAB_PASS }} # Your user password
        host-port: 3306 # MySQL host port
        container-port: 3306 # MySQL container port

    - name: Configure Env
      run: |
        echo > .env
        echo DATAB_HOST=localhost >> .env
        echo DATAB_USER=${{ secrets.DATAB_USER }} >> .env
        echo DATAB_PASS=${{ secrets.DATAB_PASS }} >> .env
        echo DATAB_NAME=${{ secrets.DATAB_NAME }} >> .env
        echo PORT=3000 >> .env

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Check Secrets
      run: |
        echo "DB_USER is set: ${{ secrets.DATAB_USER }}"
        echo "DB_NAME is set: ${{ secrets.DATAB_NAME }}"
