name: Integration Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  connect-mysql:
    runs-on: ubuntu-latest

    env:
      DATAB_HOST: ${{ secrets.MYSQL_SERVER_URL }}
      DATAB_USER: ${{ secrets.MYSQL_USERNAME }}
      DATAB_PASS: ${{ secrets.MYSQL_PASSWORD }}
      DATAB_NAME: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MySQL client
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"

      - name: Set MySQL Root Password
        run: |
          mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}';"

      - name: Create Database
        run: |
          mysql -u root -p"${{ secrets.MYSQL_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.MYSQL_DATABASE }};"

      - name: Echo Databases
        run: |
          echo "Databases in MySQL Server:"
          mysql -u root -p"${{ secrets.MYSQL_PASSWORD }}" -e "SHOW DATABASES;"

      - name: Install dependencies
        run: npm install

      - name: Migrate Database (if needed)
        run: |
          # Add any migration command if you're using migrations
          # Example: npm run migrate

      - name: Test Connection to MySQL
        run: |
          mysql -h ${{ secrets.MYSQL_SERVER_URL }} -u ${{ secrets.MYSQL_USERNAME }} -p"${{ secrets.MYSQL_PASSWORD }}" -e "SELECT VERSION();"
        
      - name: Run Tests
        run: npm test
        env:
          DATAB_HOST: ${{ secrets.MYSQL_SERVER_URL }}
          DATAB_USER: ${{ secrets.MYSQL_USERNAME }}
          DATAB_PASS: ${{ secrets.MYSQL_PASSWORD }}
          DATAB_NAME: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          NODE_ENV: test

      - name: Grant All Privileges
        run: |
          mysql -u root -p"${{ secrets.MYSQL_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '${{ secrets.MYSQL_PASSWORD }}' WITH GRANT OPTION;"

      - name: Stop MySQL Server Connection
        run: |
          # Check if the MySQL server is running and stop it
          if mysqladmin -u root -p"${{ secrets.MYSQL_PASSWORD }}" ping; then
            echo "Stopping MySQL server..."
            mysqladmin -u root -p"${{ secrets.MYSQL_PASSWORD }}" shutdown
          else
            echo "MySQL server is not running."
          fi
