name: Webapp Testing for Writtenss

on:
  pull_request:
    branches:
      - main  

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Shut down Default MySQL
      run: |
        sudo systemctl stop mysql || true  # Shutdown the Default MySQL service if it exists

    - name: Set up MySQL in Docker
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql-version: '5.7'  # Specify the version if needed
        mysql-root-password: 'root'  # Set root password
        port: 3306  # Ensure you are using the same port
        database: ${{ secrets.DATAB_NAME }}  # Create the database
        user: ${{ secrets.DATAB_USER }}  # Create the user
        password: ${{ secrets.DATAB_PASS }}  # Set user password

    - name: Configure Env
      run: |
        echo > .env
        echo DATAB_HOST=localhost >> .env
        echo DATAB_USER=${{ secrets.DATAB_USER }} >> .env
        echo DATAB_PASS=${{ secrets.DATAB_PASS }} >> .env
        echo DATAB_NAME=${{ secrets.DATAB_NAME }} >> .env
        echo PORT=3000 >> .env

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Shut down MySQL after tests
      run: sudo systemctl stop mysql  # Shutdown MySQL service after tests
